"""initial_schema

Revision ID: 3ece7dfc2a87
Revises: 
Create Date: 2026-03-04 01:40:10.140318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ece7dfc2a87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('api_config', sa.Text(), nullable=False),
    sa.Column('input_schema', sa.Text(), nullable=False),
    sa.Column('output_schema', sa.Text(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_subjects_name'), 'data_subjects', ['name'], unique=True)
    op.create_table('event_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attributes', sa.Text(), nullable=False),
    sa.Column('diagnosis_skill_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_types_name'), 'event_types', ['name'], unique=True)
    op.create_table('system_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_parameters_id'), 'system_parameters', ['id'], unique=False)
    op.create_index(op.f('ix_system_parameters_key'), 'system_parameters', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incremented primary key'),
    sa.Column('username', sa.String(length=150), nullable=False, comment='Unique username for the user'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique email address for the user'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Bcrypt-hashed password; plain-text passwords are never stored'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Whether the user account is active'),
    sa.Column('is_superuser', sa.Boolean(), server_default='0', nullable=False, comment='Whether the user has superuser (admin) privileges'),
    sa.Column('roles', sa.Text(), server_default='[]', nullable=False, comment='JSON-encoded list of roles: it_admin, expert_pe, general_user'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of when this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the last update to this record'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incremented primary key'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Title of the item'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional long-form description of the item'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Whether the item is active/visible'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='Foreign key referencing the owning user'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of when this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the last update to this record'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_owner_id'), 'items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)
    op.create_table('mcp_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data_subject_id', sa.Integer(), nullable=False),
    sa.Column('processing_intent', sa.Text(), nullable=False),
    sa.Column('processing_script', sa.Text(), nullable=True),
    sa.Column('output_schema', sa.Text(), nullable=True),
    sa.Column('ui_render_config', sa.Text(), nullable=True),
    sa.Column('input_definition', sa.Text(), nullable=True),
    sa.Column('sample_output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_subject_id'], ['data_subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_definitions_data_subject_id'), 'mcp_definitions', ['data_subject_id'], unique=False)
    op.create_index(op.f('ix_mcp_definitions_name'), 'mcp_definitions', ['name'], unique=True)
    op.create_table('skill_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('mcp_ids', sa.Text(), nullable=False),
    sa.Column('param_mappings', sa.Text(), nullable=True),
    sa.Column('problem_subject', sa.String(length=300), nullable=True),
    sa.Column('diagnostic_prompt', sa.Text(), nullable=True),
    sa.Column('human_recommendation', sa.Text(), nullable=True),
    sa.Column('last_diagnosis_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_definitions_event_type_id'), 'skill_definitions', ['event_type_id'], unique=False)
    op.create_index(op.f('ix_skill_definitions_name'), 'skill_definitions', ['name'], unique=True)
    op.create_table('routine_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('preset_parameters', sa.Text(), nullable=False),
    sa.Column('trigger_event_id', sa.Integer(), nullable=True),
    sa.Column('event_param_mappings', sa.Text(), nullable=True),
    sa.Column('schedule_interval', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.Text(), nullable=True),
    sa.Column('last_run_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['event_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_checks_name'), 'routine_checks', ['name'], unique=False)
    op.create_index(op.f('ix_routine_checks_skill_id'), 'routine_checks', ['skill_id'], unique=False)
    op.create_table('generated_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('source_skill_id', sa.Integer(), nullable=False),
    sa.Column('source_routine_check_id', sa.Integer(), nullable=True),
    sa.Column('mapped_parameters', sa.Text(), nullable=False),
    sa.Column('skill_conclusion', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_routine_check_id'], ['routine_checks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_skill_id'], ['skill_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_events_event_type_id'), 'generated_events', ['event_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_events_event_type_id'), table_name='generated_events')
    op.drop_table('generated_events')
    op.drop_index(op.f('ix_routine_checks_skill_id'), table_name='routine_checks')
    op.drop_index(op.f('ix_routine_checks_name'), table_name='routine_checks')
    op.drop_table('routine_checks')
    op.drop_index(op.f('ix_skill_definitions_name'), table_name='skill_definitions')
    op.drop_index(op.f('ix_skill_definitions_event_type_id'), table_name='skill_definitions')
    op.drop_table('skill_definitions')
    op.drop_index(op.f('ix_mcp_definitions_name'), table_name='mcp_definitions')
    op.drop_index(op.f('ix_mcp_definitions_data_subject_id'), table_name='mcp_definitions')
    op.drop_table('mcp_definitions')
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_index(op.f('ix_items_owner_id'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_parameters_key'), table_name='system_parameters')
    op.drop_index(op.f('ix_system_parameters_id'), table_name='system_parameters')
    op.drop_table('system_parameters')
    op.drop_index(op.f('ix_event_types_name'), table_name='event_types')
    op.drop_table('event_types')
    op.drop_index(op.f('ix_data_subjects_name'), table_name='data_subjects')
    op.drop_table('data_subjects')
    # ### end Alembic commands ###
